### ISSUE TITLE
"BrowserModule has already been loaded" error when importing ObsAutocompleteModule

### ISSUE THREAD

**Issue by ahmed-anas** [OasisDigital/angular-material-obs-autocomplete#3]
I'm trying to integrate this module. `ObsAutocompleteModule` seems to be the core module that needs to be imported to use the component. However this module imports the `BrowserModule` which  means that I get the above mentioned exception if I want to use this module in a sub-module

**Comment by kylecordes** [comment]
Ah... It appears I was not supposed to import BrowserAnimationsModule, I will investigate and fix later today.

**Comment by kylecordes** [comment]
Fix in version 0.11.3 .
